# https://travis-ci.org/kecnry/autofig

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: trusty

env:
    global:
        # Set defaults to avoid repeating in most cases
        - CONDA_DEPENDENCIES='matplotlib
        - PIP_DEPENDENCIES='nose'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try with lowest supported numpy/astropy (only with python 2.7)
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0'

        # Try with stable versions of numpy/astropy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        # Try with dev version of numpy (only with python 3.6)
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=dev ASTROPY_VERSION=stable'

    allow_failures:
      - env: NUMPY_VERSION=dev

before_install:
    - rvm get head
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update;
      fi;

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - nosetests -v -s -d -w tests/;
