# https://travis-ci.org/kecnry/autofig

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: trusty

env:
    global:
        # Set defaults to avoid repeating in most cases
        - CONDA_DEPENDENCIES='matplotlib'
        - PIP_DEPENDENCIES='nose'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

          # Python 2.7: lowest version, stable, dev
        - os: linux
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=1.4.3 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0'

        - os: linux
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=2.2 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        # astropy and matplotlib dev doesn't support python < 3.5
        - os: linux
          env: PYTHON_VERSION=2.7 MATPLOTLIB_VERSION=2.2 NUMPY_VERSION=dev ASTROPY_VERSION=stable'

        # Python 3.6: lowest version, stable, dev
        # note: NUMPY 1.10 is not supported with PYTHON 3.6, so we'll use stable instead
        - os: linux
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=1.4.3 NUMPY_VERSION=stable ASTROPY_VERSION=1.0'

        - os: linux
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=2.2 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

        - os: linux
          env: PYTHON_VERSION=3.6 MATPLOTLIB_VERSION=dev NUMPY_VERSION=dev ASTROPY_VERSION=dev'

    allow_failures:
      - env: NUMPY_VERSION=dev

before_install:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update;
      fi;

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - nosetests -v -s -d -w tests/;
